# Generated by Django 4.0.4 on 2025-04-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0020_motivo_estoquesaida_estoqueentrada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoquesaida',
            options={'ordering': ['id_produto', 'validade', 'motivo'], 'verbose_name': 'Estoque Saida', 'verbose_name_plural': 'Estoque Saidas'},
        ),
        migrations.RenameField(
            model_name='estoquesaida',
            old_name='quantidade',
            new_name='quantidade_saida',
        ),
        migrations.RemoveField(
            model_name='estoquesaida',
            name='id_fonte',
        ),
    ]
